List view component
V-X-L-U/Do-This-First pull request #15
Opened 2022-07-18 20:17 UTC by nicholaas11

- [x] Add `TaskListItem` component
- [x] Add `PrereqListItem` component
- [x] Implement general list view component
- [x] Add task colors
- [x] Add react-icons dependency

2022-07-21 22:40 UTC, V-X-L-U requested changes
Mostly looks good, just a couple of code-styling comments and minor CSS changes needed.

2022-07-23 17:39 UTC, nicholaas11 commented on frontend/src/components/ListView/ListView.module.css
> +  height: 7vh;
True, changed height to 50px instead

2022-07-23 19:39 UTC, V-X-L-U approved these changes, later dismissed

2022-07-23 19:45 UTC, V-X-L-U approved these changes

2022-07-23 19:45 UTC, merged